name: MLOps Assignment Workflow

on:
  push:
    branches:
      - feature/dummy

jobs:
  run-main-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 3.  new print/echo statement in GitHub actions yaml file
    - name: Echo statement
      run: echo "***FOR MLOPS QUIZ***Running MLOps Assignment Workflow "

    - name: Run main script
      run: docker_run.sh
